apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: deploymenthpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rollout-bluegreen
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10
